version: 0.2
phases: 
  pre_build: 
    commands: 
    
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 570195150291.dkr.ecr.ap-south-1.amazonaws.com
  
  build: 
    commands: 
    - echo install npm libraries `date` 
    #- echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - ls -ltr
 
    - npm i
    - npm install -g dotenv-cli
    - echo Starting to build 'date'
    - npm run build:prod
    - aws s3 rm s3://pro.credr.com --recursive
    - aws s3 cp build/ s3://pro.credr.com --recursive --acl public-read
    - echo 'Successfully uploaded the dist'
    - aws cloudfront create-invalidation --distribution-id E17QPV2QQAE2F3 --path "/*"
    - echo 'Successfully created invalidation'
